version: "3.9"

services:
  rigging:
    build: .
    image: drawing-spinup-rigging:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DATA_ROOT: /data
      SERVER_GPU_IDS: "[0,1,2,3]"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./data:/data
      - ./DrawingSpinUp:/opt/app/DrawingSpinUp
